### ISSUE TITLE
BARControl on windows: "localhost" is always added to barcontrol.cfg as 1st entry

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#12]
Situation: BARserver is running on a remote (Linux) host, BARControl is started on local Windows host.
barcontrol.cfg currently only contains the following correct lines:

```
# Server settings
server = svr:38523
server-ca-file = ""
server-keystore-file = ""
no-tls = no
force-tls = no
tls-insecure = no
role = EXPERT
```

When one now starts BARControl, it still tries to connect to localhost first, giving an error:
![grafik](https://github.com/user-attachments/assets/45e554c0-d00b-4a63-af24-881bac332077)
Of course, one can select the correct entry in the drop-down list, but it is always the 2nd entry, so auto-connect always fails.

After running BARControl, the erroneous line "server = localhost:38523" is added to the barcontrol.cfg file:

```
# Server settings
server = localhost:38523
server = svr:38523
server-ca-file = ""
server-keystore-file = ""
no-tls = no
force-tls = no
tls-insecure = no
role = EXPERT
```
This behaviour has been like this at least since version 0.21, maybe even earlier. I just never reported it yet.

**Comment by torsten-rupp** [comment]
fixed with release 25

localhost is the default server name if no other name is given and stored in the configuration file. Of course in the above settings "srv" should be used.
