### ISSUE TITLE
BARControl: Detection of architecture not working reliable with Amazon Coretto JVM (Windows)

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#13]
Auto-detection of architecture seems to be broken in 24a, at least with Amazon Coretto Java x64. The error
`ERROR: cannot detect data model (32/64 bit) - VM failure?` is displayed, and BARControl is not being started.

The underlying problem here seems to be the following:

```
java.exe -Xmx128m -enableassertions -jar C:\Users\Chris\Desktop\BAR GUI\barcontrol-windows_64.jar
Error: Unable to access jarfile C:\Users\Chris\Desktop\BAR
```
Looks like a missing quotation of the file-path, leading to a truncated path breaking at the whitespace.

I just wonder why this did not happen with version 0.22f I was running a long time w/o any problems?

**Comment by ChrisTG742** [comment]
Fixed "barcontrol.cmd" attached
[barcontrol.txt](https://github.com/user-attachments/files/17270401/barcontrol.txt)

**Comment by torsten-rupp** [comment]
Yes the quotes are missing.

Fixed with release 25

Maybe the path were barcontrol.bat is stored changed at some time to a path with a space?
