### ISSUE TITLE
barcontrol saves wrong window-settings on Windows / missing fields in GUI

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#14]
barcontrol seems to save wrong window-settings into barcontrol.cfg when run on Windows x64.

First run (everything is okay):
![bar1](https://github.com/user-attachments/assets/56ef2cf2-4d86-4680-9cf3-bc2761c9b31c)

2nd run (lower bar and list is missing):
![bar2](https://github.com/user-attachments/assets/bdc17e4d-9f94-4381-a74c-906b8583aaf5)

The missing parts are not restorable by trying to pull the window larger or smaller, also chaning the divisions inside the window does not bring it up again.
Only solution ATM is, to delete all "-columns" settings from barcontrol.cfg.
For the next start, the missing fields are visible again then.

Last tested on v24a.

**Comment by torsten-rupp** [comment]
Can you reproduce this with release 25, too?

**Comment by torsten-rupp** [comment]
Verified with 24a that it is possible to move the sash (the horizontal divider)  out of the window thus it cannot be reverted. With the next the sash position could become out of the valid range and the bottom part of the window is missing.

There is a fix with commit 5bb8fe6501d9562bc8fee29c22a348dde4999b48 for the sash size calculation which is part of release 25. There I'm not able to move the sash into an invalid position.

**Comment by ChrisTG742** [comment]
> Can you reproduce this with release 25, too?
Yes, it's the same with barserver 25 and GUI 25 on Windows.

**Comment by torsten-rupp** [comment]
fixed with commit 0aace6a3b7e85475055bf4f9651fc1dcd1701001
