### ISSUE TITLE
Wrong warning in log about deprecated parameter "slave-host-force-tls"

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#18]
The log says:

`2024-10-27 16:13:14> Warning: Configuration value 'slave-host-force-tls' is deprecated. Use 'slave-tls-mode' instead in /etc/bar/jobs/Backup System, line 47: 'slave-host-force-tls = no'`

But when I do `grep -r 'slave-host-force-tls' /etc/bar/bar.cfg`, there is nothing found.

**Comment by torsten-rupp** [comment]
I assume it is in some of the job files in /etc/bar/jobs. These settings overwrite the general settings from bar.cfg.

**Comment by ChrisTG742** [comment]
Ah, my bad! I did not read carefully enough :-D

There indeed was a setting "slave-host-force-tls = no" in "/etc/bar/jobs/Backup System".
Isn't that updated by the new parameter when I edit something in the job via GUI? If not, why not?

**Comment by torsten-rupp** [comment]
No, currently on the warning is printed. The deprecated parameters are not automatically replaced. But it is a good idea to do that when it is possible.
