### ISSUE TITLE
Display refresh broken in 0.22f for slave jobs

### ISSUE THREAD

**Issue by ChrisTG742** [torsten-rupp/bar#2]
In 0.22f, the refresh of the job display in the GUI seems to be broken when the backup is running on a slave node.
The job actually runs fine, but the display just says "done" while there is no other progress visible. Also, all other readings stay on their initial values. I did not notive this with 0.22e before.

Edit: This only seems to happen for "dry-run" with a slave backup job.

**Comment by torsten-rupp** [comment]
Thank you Chris. I will have  look on that and fix it.

**Comment by torsten-rupp** [comment]
Thank you Chris. I will have  look on that and fix it.

**Comment by torsten-rupp** [comment]
Fixed with commit b8d481a122d9b7126826a652dd8940d84397ba22
